//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por PROYECTO PA.rc
//
#define DLG_CAM_PROD                    3
#define DLG_REG                         5
#define DLG_INF                         9
#define DLG_LOGIN                       101
#define IDD_Registro                    103
#define DLG_NEW_ENVIO                   103
#define DLG_PRIN                        105
#define IDR_MENU1                       109
#define DLG_Alta_producto               110
#define DLG_Baja_Producto               112
#define DLG_ELIMINAR_PROD               114
#define DLG_Info_vendedor               118
#define DLG_Cambio_producto             120
#define DLG_Cambios_productos           122
#define DLG_MIS_PRODUCTOS               124
#define DLG_CAM_INFO                    128
#define DLG_ENVIOS_EDITAR               130
#define TXT_LUSER                       1002
#define TXT_LPASS                       1003
#define BTN_Reg                         1004
#define BTN_LOG                         1005
#define BTN_NUSER                       1007
#define TXT_NUSER                       1010
#define TXT_NPASSWORD                   1011
#define BTN_RCAN                        1012
#define TXT_INF_VENDEDOR                1013
#define TXT_INF_ALIAS                   1014
#define BTN_INF_ACEP                    1015
#define BTN_NEW_ENVIO                   1017
#define TXT_PROD_NOM                    1018
#define TXT_PROD_INV                    1019
#define TXT_PROD_COD                    1020
#define TXT_PROD_MARCA                  1021
#define TXT_PROD_DESC                   1022
#define TXT_CODIGO_BUSQUEDA             1023
#define BTN_ACP_BAJA                    1024
#define IDC_LIST1                       1025
#define DTP_fecha                       1029
#define IDC_COMBO1                      1030
#define IDC_EDIT1                       1031
#define TXT_ENVIO_MENSAJE               1031
#define TXT_ENVIOS_DIRECCION            1031
#define IDC_EDIT2                       1032
#define TXT_ENVIO_ESTADO                1032
#define TXT_ENVIOS_FECHA                1032
#define IDC_EDIT3                       1033
#define TXT_ENVIO_CIUDAD                1033
#define TXT_ENVIOS_PRODUCTO             1033
#define IDC_EDIT4                       1034
#define TXT_ENVIO_COLONIA               1034
#define TXT_ENVIOS_CANTIDAD             1034
#define IDC_EDIT5                       1035
#define TXT_ENVIO_CALLE                 1035
#define TXT_ENVIOS_ESTATUS              1035
#define LBL_Fecha                       1036
#define LBL_Nombre_vendedor             1037
#define LBL_Nombre_empresa              1038
#define BTN_NPROD                       1039
#define BTN_BAJA_CANCEL                 1040
#define BTN_CAM_PROD                    1041
#define LBL_ID_vendedor                 1042
#define BTN_CNL_INFO                    1043
#define TXT_PROD_Cam                    1044
#define BTN_CAN_CAM                     1045
#define TXT_PROD_MONTO_SELECTED         1046
#define LB_PRODUCTOS                    1048
#define BTN_Volver_Prod                 1049
#define TXT_PROD_NOMBRE                 1050
#define TXT_PROD_CAN_SELECTED           1051
#define TXT_PROD_COD_SELECTED           1052
#define TEXT_PROD_MARCA_SELECTED        1053
#define TXT_PROD_DES_SELECTED           1054
#define TXT_PROD_MONTO                  1055
#define LBL_CAMBIO_NOMBRE               1056
#define LBL_CAMBIO_CANT                 1057
#define LBL_CAMBIO_CODIGO               1058
#define LBL_CAMBIO_MARCA                1059
#define LBL_CAMBIO_DES                  1060
#define LBL_CAMBIO_MONTO                1061
#define BTN_CAMBIOS_VOLVER              1062
#define BTN_CAMBIOS_SEGUIR              1063
#define TXT_CAM_MONT                    1064
#define TXT_CAM_NOM                     1065
#define TXT_CAM_CAN                     1066
#define TXT_CAM_COD                     1067
#define TXT_CAM_MARC                    1068
#define TXT_CAM_DESC                    1069
#define BTN_CAM_ACP                     1070
#define BTN_CAM_CAN                     1071
#define BTN_CAM_INFV                    1072
#define TXT_Cam_inf                     1073
#define TXT_CAM_alias                   1074
#define BTN_Acp_cam_inf                 1075
#define BTN_INFO_IMAGEN                 1076
#define PB_IMAGEN                       1077
#define PB_INFO_IMG                     1078
#define CB_PRODUCTOS                    1079
#define TXT_ENVIO_CANTIDAD              1080
#define BTN_ACEPTAR_ENVIO               1081
#define BTN_CANCELAR_ENVIO              1082
#define LBL_MONTO_ENVIO                 1083
#define Direccion                       1084
#define BTN_CANCEL_ALTA                 1085
#define LB_ENVIOS                       1087
#define ID_PRODUCTOS_ALTA               40001
#define ID_PRODUCTOS_BAJA               40002
#define ID_PRODUCTOS_CAMBIO             40003
#define ID_INFORMACIONDELVENDEDOR       40004
#define ID_ENVIOS                       40005
#define ID_ENVIOS_NUEVOENVIO            40006
#define ID_SALIR                        40007
#define ID_ENVIOS40008                  40008
#define ID_PRODUCTOS_MISPRODUCTOS       40009
#define ID_ENVIOS_COMPRARPRODUCTOS      40010
#define ID_ENVIOS_CANCELARUNENVIO       40011
#define ID_ENVIOS_EDITARUNENVIO         40012

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         40013
#define _APS_NEXT_CONTROL_VALUE         1088
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
